function COM = COM_fcn(l1,l2,l4,lc1,lc2,lc3,lc4,lc5,m1,m2,m3,m4,m5,q1,q2,q3,q4,q5)
%COM_FCN
%    COM = COM_FCN(L1,L2,L4,LC1,LC2,LC3,LC4,LC5,M1,M2,M3,M4,M5,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Aug-2020 15:50:14

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = cos(t3);
t5 = l1.*t4;
t6 = q2+t2;
t7 = cos(t6);
t8 = l2.*t7;
t9 = q4+t2;
t10 = cos(t9);
t11 = q5+t2;
t12 = sin(t3);
t13 = l1.*t12;
t14 = sin(t6);
t15 = l2.*t14;
t16 = q3+t2;
t17 = sin(t9);
t18 = m1+m2+m3+m4+m5;
t19 = 1.0./t18;
COM = [t19.*(m4.*(t5+t8-lc4.*t10)+m3.*(t5+t8+lc3.*cos(t16))+m2.*(t5+lc2.*t7)+m5.*(t5+t8-l4.*t10-lc5.*cos(t11))+lc1.*m1.*t4);t19.*(m5.*(t13+t15-l4.*t17-lc5.*sin(t11))+m4.*(t13+t15-lc4.*t17)+m3.*(t13+t15+lc3.*sin(t16))+m2.*(t13+lc2.*t14)+lc1.*m1.*t12)];
