function COM_segments = COM_segments_fcn(l1,l2,l4,lc1,lc2,lc3,lc4,lc5,q1,q2,q3,q4,q5)
%COM_SEGMENTS_FCN
%    COM_SEGMENTS = COM_SEGMENTS_FCN(L1,L2,L4,LC1,LC2,LC3,LC4,LC5,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Nov-2020 10:34:08

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = cos(t3);
t5 = sin(t3);
t6 = q2+t2;
t7 = l1.*t4;
t8 = cos(t6);
t9 = l1.*t5;
t10 = sin(t6);
t11 = q3+t2;
t12 = l2.*t8;
t13 = l2.*t10;
t14 = q4+t2;
t15 = cos(t14);
t16 = sin(t14);
t17 = q5+t2;
COM_segments = [lc1.*t4;lc1.*t5;0.0;t7+lc2.*t8;t9+lc2.*t10;0.0;t7+t12+lc3.*cos(t11);t9+t13+lc3.*sin(t11);0.0;t7+t12-lc4.*t15;t9+t13-lc4.*t16;0.0;t7+t12-l4.*t15-lc5.*cos(t17);t9+t13-l4.*t16-lc5.*sin(t17);0.0];
