function COMvel = COMvel_fcn(dq1,l1,l2,l4,lc1,lc5,m1,m2,m3,m4,m5,q1,q2,q4,q5)
%COMVEL_FCN
%    COMVEL = COMVEL_FCN(DQ1,L1,L2,L4,LC1,LC5,M1,M2,M3,M4,M5,Q1,Q2,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Aug-2020 15:50:15

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = sin(t3);
t5 = m1+m2+m3+m4+m5;
t6 = 1.0./t5;
t7 = q2+t2;
t8 = q4+t2;
t9 = q5+t2;
t10 = cos(t3);
COMvel = [-t6.*(-m5.*(l1.*t10+l2.*cos(t7)-l4.*cos(t8)-lc5.*cos(t9))+dq1.*lc1.*m1.*t4+dq1.*lc1.*m2.*t4+dq1.*lc1.*m3.*t4+dq1.*lc1.*m4.*t4);t6.*(m5.*(l1.*t4+l2.*sin(t7)-l4.*sin(t8)-lc5.*sin(t9))+dq1.*lc1.*m1.*t10+dq1.*lc1.*m2.*t10+dq1.*lc1.*m3.*t10+dq1.*lc1.*m4.*t10);0.0];
